environment: stage

redis_host: master.mocha-stage-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 852
  replicas: 1

secret:
  redis_pass: automate-all-the-things-stage
